#!/usr/bin/env python3
"""
uds2c.py - generate the UDS module/DID tables from can-db/uds_catalog.json.

Output: src/gen/s2_uds_gen.h / .c
  - s2_uds_modules[]: request/response ids per diagnostic module
  - s2_uds_dids[]   : every catalogued DID with its status and whether it is
                      0x27 SecurityAccess-locked (the poller skips locked and
                      refuted entries; decoders live in src/uds_decode.c)

Usage: python3 tools/uds2c.py [--catalog PATH] [--out-dir DIR] [--check]
"""
import argparse
import json
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DEFAULT_CATALOG = os.path.join(ROOT, "can-db", "uds_catalog.json")
DEFAULT_OUT = os.path.join(ROOT, "src", "gen")

STATUS = {"confirmed": "S2_UDS_CONFIRMED", "candidate": "S2_UDS_CANDIDATE", "refuted": "S2_UDS_REFUTED"}


def c_str(s, limit=None):
    s = s.replace("\\", "\\\\").replace('"', '\\"').replace("\n", " ")
    if limit and len(s) > limit:
        s = s[:limit - 3] + "..."
    return '"' + s + '"'


def is_locked(did):
    text = " ".join(str(did.get(k, "")) for k in ("name", "encoding_or_scale", "evidence")).lower()
    return "security-locked" in text or "securityaccess-locked" in text


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--catalog", default=DEFAULT_CATALOG)
    ap.add_argument("--out-dir", default=DEFAULT_OUT)
    ap.add_argument("--check", action="store_true")
    args = ap.parse_args()

    with open(args.catalog, encoding="utf-8") as f:
        cat = json.load(f)
    modules = cat["modules"]
    rel = os.path.relpath(args.catalog, ROOT)
    generated = cat.get("_meta", {}).get("generated", "")

    h = []
    h.append("/* Generated by tools/uds2c.py from %s (catalog generated %s) - DO NOT EDIT. */" % (rel, generated))
    h.append("#pragma once")
    h.append("")
    h.append("#include <stddef.h>")
    h.append("#include <stdint.h>")
    h.append("")
    h.append("typedef enum {")
    h.append("    S2_UDS_CONFIRMED = 0,  /* corroborated across >= 2 sessions or pinned by direct count */")
    h.append("    S2_UDS_CANDIDATE,      /* structure holds, scale/offset/semantics still open */")
    h.append("    S2_UDS_REFUTED,        /* earlier attribution disproven - kept so it is not re-attempted */")
    h.append("} s2_uds_status_t;")
    h.append("")
    h.append("typedef enum {")
    for i, key in enumerate(modules):
        h.append("    S2_UDS_MOD_%s = %d," % (key, i))
    h.append("    S2_UDS_MOD__COUNT = %d," % len(modules))
    h.append("} s2_uds_module_id_t;")
    h.append("")
    h.append("typedef struct {")
    h.append("    const char *name;      /* short key, e.g. \"RESS\" */")
    h.append("    const char *role;")
    h.append("    uint16_t req_id;       /* physical request id */")
    h.append("    uint16_t resp_id;      /* response id (req + 8) */")
    h.append("} s2_uds_module_t;")
    h.append("")
    h.append("typedef struct {")
    h.append("    uint8_t module;        /* s2_uds_module_id_t */")
    h.append("    uint8_t status;        /* s2_uds_status_t */")
    h.append("    uint8_t locked;        /* 0x27 SecurityAccess required - never polled */")
    h.append("    uint16_t did;")
    h.append("    const char *name;")
    h.append("    const char *encoding;  /* encoding_or_scale from the catalog */")
    h.append("} s2_uds_did_t;")
    h.append("")
    h.append("extern const s2_uds_module_t s2_uds_modules[];")
    h.append("extern const size_t s2_uds_module_count;")
    h.append("extern const s2_uds_did_t s2_uds_dids[];")
    h.append("extern const size_t s2_uds_did_count;")
    h.append("")
    h.append("/* Module whose response id matches, or NULL. */")
    h.append("const s2_uds_module_t *s2_uds_module_by_resp(uint32_t can_id);")
    h.append("const s2_uds_did_t *s2_uds_find_did(uint8_t module, uint16_t did);")
    h.append("")

    c = []
    c.append("/* Generated by tools/uds2c.py from %s - DO NOT EDIT. */" % rel)
    c.append("#include \"s2_uds_gen.h\"")
    c.append("")
    c.append("const s2_uds_module_t s2_uds_modules[] = {")
    for key, mod in modules.items():
        req = int(mod["req"], 16)
        resp = int(mod["resp"], 16)
        c.append("    [S2_UDS_MOD_%s] = { .name = %s, .role = %s, .req_id = 0x%03X, .resp_id = 0x%03X },"
                 % (key, c_str(key), c_str(mod.get("role", ""), 120), req, resp))
    c.append("};")
    c.append("const size_t s2_uds_module_count = %d;" % len(modules))
    c.append("")
    c.append("const s2_uds_did_t s2_uds_dids[] = {")
    n = 0
    for key, mod in modules.items():
        for did_hex, did in sorted(mod.get("dids", {}).items(), key=lambda kv: int(kv[0], 16)):
            status = STATUS.get(did.get("status", "candidate"), "S2_UDS_CANDIDATE")
            c.append("    { .module = S2_UDS_MOD_%s, .status = %s, .locked = %d, .did = 0x%04X,"
                     % (key, status, 1 if is_locked(did) else 0, int(did_hex, 16)))
            c.append("      .name = %s," % c_str(did.get("name", ""), 110))
            c.append("      .encoding = %s }," % c_str(did.get("encoding_or_scale", ""), 160))
            n += 1
    c.append("};")
    c.append("const size_t s2_uds_did_count = %d;" % n)
    c.append("")
    c.append("const s2_uds_module_t *s2_uds_module_by_resp(uint32_t can_id)")
    c.append("{")
    c.append("    for (size_t i = 0; i < s2_uds_module_count; i++) {")
    c.append("        if (s2_uds_modules[i].resp_id == can_id) {")
    c.append("            return &s2_uds_modules[i];")
    c.append("        }")
    c.append("    }")
    c.append("    return NULL;")
    c.append("}")
    c.append("")
    c.append("const s2_uds_did_t *s2_uds_find_did(uint8_t module, uint16_t did)")
    c.append("{")
    c.append("    for (size_t i = 0; i < s2_uds_did_count; i++) {")
    c.append("        if (s2_uds_dids[i].module == module && s2_uds_dids[i].did == did) {")
    c.append("            return &s2_uds_dids[i];")
    c.append("        }")
    c.append("    }")
    c.append("    return NULL;")
    c.append("}")
    c.append("")

    outputs = {
        os.path.join(args.out_dir, "s2_uds_gen.h"): "\n".join(h) + "\n",
        os.path.join(args.out_dir, "s2_uds_gen.c"): "\n".join(c) + "\n",
    }
    if args.check:
        stale = [p for p, content in outputs.items()
                 if not os.path.exists(p) or open(p, encoding="utf-8").read() != content]
        if stale:
            print("stale generated files: " + ", ".join(os.path.relpath(p, ROOT) for p in stale))
            return 1
        print("generated files are up to date")
        return 0
    os.makedirs(args.out_dir, exist_ok=True)
    for path, content in outputs.items():
        with open(path, "w", encoding="utf-8") as f:
            f.write(content)
    locked = sum(1 for m in modules.values() for d in m["dids"].values() if is_locked(d))
    refuted = sum(1 for m in modules.values() for d in m["dids"].values() if d.get("status") == "refuted")
    print("%d modules, %d DIDs (%d locked, %d refuted) -> %s" % (len(modules), n, locked, refuted, os.path.relpath(args.out_dir, ROOT)))
    return 0


if __name__ == "__main__":
    sys.exit(main())
